In [7]:
import pandas as pd
import json
import glob

In [8]:
results_dir = '../results'

In [9]:
all_results = glob.glob('../results/*.json')

table_data = []
for result in all_results:
    with open(result, 'r') as f:
        data = json.load(f)
        for k, v in data.items():
            if k in ['Accuracy', 'IoU', 'AP']:
                data[k] = v['mean']        
            if k == 'train_config':
                data[k] = str(v)
        table_data.append(data)

In [10]:
df = pd.DataFrame(table_data)
df

,AP,IoU,Accuracy,number_of_samples,depth_channel_representation_mode,window_len,train_config,multiple_digits,model_path
0,0.181437,0.183248,0.935127,1907,zeros,20,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
1,0.347404,0.437394,0.954969,1907,zeros,20,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
2,0.422653,0.561224,0.961449,1907,zeros,20,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
3,0.223960,0.252343,0.939775,2525,zeros,10,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
4,0.216238,0.221131,0.930674,2525,zeros,10,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
5,0.101386,0.101332,0.931328,2525,zeros,10,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
6,0.176436,0.213375,0.946270,2525,zeros,10,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
7,0.347723,0.437653,0.953474,2525,zeros,10,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
8,0.320396,0.347559,0.943864,2525,zeros,10,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
9,0.321386,0.393821,0.950745,2525,zeros,10,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
10,0.316238,0.395757,0.952032,2525,zeros,10,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
11,0.410297,0.569976,0.962093,2525,zeros,10,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
12,0.410693,0.573816,0.962461,2525,zeros,10,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
13,0.422970,0.586082,0.961897,2525,zeros,10,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
14,0.401980,0.546483,0.958183,2525,zeros,10,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
15,0.246931,0.281081,0.941241,2525,zeros,10,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
16,0.333069,0.416933,0.952324,2525,zeros,10,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
17,0.376832,0.501828,0.958474,2525,zeros,10,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
18,0.139748,0.112466,0.920653,1907,zeros,20,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
19,0.211851,0.141732,0.910963,1907,zeros,20,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
20,0.189565,0.199336,0.931114,1907,zeros,20,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
21,0.182223,0.171834,0.933973,1907,zeros,20,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
22,0.318301,0.406847,0.954895,1907,zeros,20,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
23,0.329837,0.396060,0.949578,1907,zeros,20,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
24,0.358679,0.434934,0.950986,1907,zeros,20,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
25,0.347404,0.414935,0.950565,1907,zeros,20,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
26,0.410855,0.552781,0.961008,1907,zeros,20,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
27,0.393550,0.523493,0.959559,1907,zeros,20,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
28,0.417672,0.549103,0.959565,1907,zeros,20,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
29,0.411641,0.559279,0.961596,1907,zeros,20,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
30,0.206503,0.218257,0.942885,1184,zeros,50,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
31,0.202703,0.214728,0.931590,1184,zeros,50,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
32,0.153294,0.102967,0.926866,1184,zeros,50,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
33,0.226774,0.251884,0.945143,1184,zeros,50,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
34,0.332770,0.369792,0.950862,1184,zeros,50,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
35,0.350929,0.417797,0.953290,1184,zeros,50,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
36,0.323902,0.399350,0.956574,1184,zeros,50,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
37,0.355997,0.427652,0.949130,1184,zeros,50,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
38,0.416385,0.553077,0.962120,1184,zeros,50,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
39,0.401605,0.529210,0.961482,1184,zeros,50,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
40,0.414696,0.553665,0.961952,1184,zeros,50,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
41,0.423986,0.558236,0.961136,1184,zeros,50,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
42,0.187500,0.204340,0.942543,1184,zeros,50,"{'epochs': 2, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
43,0.339527,0.404838,0.939795,1184,zeros,50,"{'epochs': 5, 'learning_rate': 0.001, 'layers'...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...
44,0.413851,0.558265,0.961858,1184,zeros,50,"[{'epochs': 5, 'learning_rate': 0.001, 'layers...",False,C:\Users\tfrva\OneDrive\Documenten\CSE Master\...

In [11]:
metrics = ['Accuracy', 'IoU', 'AP']
grouped = df.groupby(['window_len','train_config','multiple_digits','depth_channel_representation_mode'])
means = grouped[metrics].mean(numeric_only=True)
stds = grouped[metrics].std(numeric_only=True)
stds.rename(columns=lambda x: x + '_std', inplace=True)
counts = pd.DataFrame(grouped.size(), columns=['n'])

combined = pd.concat([means, stds, counts], axis=1)
for metric in metrics:
    combined[metric] = combined.apply(lambda x: f"{x[metric]:.4f} ± {x[f'{metric}_std']:.4f}", axis=1)
    combined.drop([f'{metric}_std'], axis=1, inplace=True)
combined.to_csv('results.csv', index=True)
combined

                                                                                                                        Accuracy  \
window_len train_config                                       multiple_digits depth_channel_representation_mode
10         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.9606 ± 0.0021
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9379 ± 0.0067
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9505 ± 0.0038
20         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.9606 ± 0.0010
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9264 ± 0.0103
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9522 ± 0.0025
50         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.9617 ± 0.0004
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9378 ± 0.0081
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.9499 ± 0.0063

                                                                                                                             IoU  \
window_len train_config                                       multiple_digits depth_channel_representation_mode
10         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.5556 ± 0.0333
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.2139 ± 0.0684
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.3983 ± 0.0335
20         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.5492 ± 0.0152
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.1617 ± 0.0347
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.4180 ± 0.0179
50         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.5505 ± 0.0121
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.1984 ± 0.0563
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.4039 ± 0.0220

                                                                                                                              AP  \
window_len train_config                                       multiple_digits depth_channel_representation_mode
10         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.4046 ± 0.0172
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.1930 ± 0.0572
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.3278 ± 0.0128
20         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.4113 ± 0.0110
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.1810 ± 0.0261
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.3403 ± 0.0161
50         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              0.4141 ± 0.0081
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              0.1954 ± 0.0274
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              0.3406 ± 0.0131

                                                                                                                 n
window_len train_config                                       multiple_digits depth_channel_representation_mode
10         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              5
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              5
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              5
20         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              5
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              5
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              5
50         [{'epochs': 5, 'learning_rate': 0.001, 'layers'... False           zeros                              5
           {'epochs': 2, 'learning_rate': 0.001, 'layers':... False           zeros                              5
           {'epochs': 5, 'learning_rate': 0.001, 'layers':... False           zeros                              5